# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b453b20a-f2ae-4f2b-8495-d1aa93cce619";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."devcrypted".device = "/dev/disk/by-uuid/1feed576-41a5-4088-a640-7213de72fc4a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2FFB-F731";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/868ec031-9c67-4a78-8d21-5d89e7b77f32"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
